In [1]:
import numpy as np
import time

X = np.random.randn(10,3)
Y = np.random.randn(1000,3)
start = time.time()
# XX = np.einsum('ij,ij->i', X, X)[:, np.newaxis]
# YY = np.einsum('ij,ij->i', Y, Y)
# XY = 2 * np.dot(X, Y.T)
# res1=np.sqrt(XX + YY - XY)

# subts = origs[:,None,:] - dests
subts = X[:,None,:] - Y
res2 = np.sqrt(np.einsum('ijk,ijk->ij',subts,subts))
end=time.time()

print(end-start)


0.0005216598510742188


In [2]:
np.max(res2,axis=1)

TypeError: _amax_dispatcher() got an unexpected keyword argument 'axix'

In [39]:
x=1.0+ np.arange(-5,6)*0.1
z=1.42+ np.arange(-5,6)*0.1
y=0.54

c=np.array(np.meshgrid(x,y,z)).T.reshape(-1,3)

In [35]:
a= np.random.randint(low=0,high=100,size=100)
a[np.argpartition(a,-4)[-4:]]


array([96, 97, 96, 99])

In [28]:
a

array([7, 8, 5, 9, 4, 9, 8, 4, 0, 9])

In [27]:
a[np.argpartition(a,-4)[-4:]]


array([8, 9, 9, 9])

In [63]:
a= np.random.randint(low=0,high=20,size=160).reshape(20,8)
a

array([[ 4, 10,  2, 19,  9,  7,  4,  2],
       [ 9, 19, 16, 14,  2,  7, 17,  2],
       [ 4, 16, 10,  6, 18,  4, 19, 14],
       [ 3, 19, 14, 12,  9,  9,  2, 19],
       [17,  3, 10,  1, 14, 19, 13,  2],
       [ 7,  0,  0, 12,  6,  9, 19, 14],
       [13,  0, 19, 11, 16, 14, 10, 10],
       [10, 15,  3, 18,  0,  9,  7, 19],
       [ 2, 11, 19, 18, 10, 10,  2, 16],
       [ 5,  2,  2, 17, 13,  7, 14,  1],
       [12, 17, 18,  6, 11,  5,  3,  8],
       [ 7,  1,  3, 15,  5, 16,  4, 13],
       [ 3, 16, 15,  2,  3,  1, 13,  5],
       [13, 15, 19, 14,  7,  9,  2,  9],
       [13, 15,  9,  7, 13, 15, 15,  5],
       [14,  3,  6,  6, 18,  1, 16, 10],
       [ 6, 14,  0, 10,  9,  0, 16, 14],
       [16, 13,  3,  5, 10, 18,  5, 14],
       [17,  7,  4, 16, 16,  0, 19,  8],
       [10, 10,  0,  4, 11,  6,  0,  3]])

In [65]:
idx=np.argpartition(a,3)[:,:3]

In [48]:
np.argwhere(a>10).reshape(-1)

array([ 0,  7, 10, 11, 17, 18])

In [100]:
a= np.random.randint(low=0,high=20,size=(4,4))
b= [1,2,3,4] 

In [3]:
a=np.array([ 0,  7, 10, 11, 17, 18])

In [12]:
b=a.reshape(2,3)
b=b.reshape(6,)
b.shape

(6,)

In [9]:
b=b.reshape(6,)

array([ 0,  7, 10, 11, 17, 18])

In [10]:
b

array([[ 0,  7, 10],
       [11, 17, 18]])